name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress --ignore=*/vendor/* .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress --ignore=*/vendor/* .

      - name: Run tests
        run: |
          # Run PHPUnit tests
          ./vendor/bin/phpunit

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd wordpress-plugin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest

    deploy-to-staging:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        needs: build-and-push

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Deploy to Staging Server
            run: |
              ssh ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_IP }} "docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest && docker-compose -f docker-compose.yml up -d"
